### ISSUE TITLE
After 1-2 action software does nothing - saved beat maps

### ISSUE THREAD

**Issue by NiteSite** [ranmd9a/beatlist#2]
You can click on Song name to organize the songs by name (It does not do this correctly) and then you can't click anything else

If you click on delete to remove a beat map it will remove the song when you delete using the 2nd prompt - you can perform this action twice (Map uninstalled Close then gets stuck in the bottom right corner)

This is ONLY on saved beat maps

**Comment by ranmd9a** [comment]
@NiteSite 
Thanks for the report.

> You can click on Song name to organize the songs by name (It does not do this correctly) and then you can't click anything else

Which version are you using? latest (v1.3.3)?
How many songs do you have? I have about 3600 songs, but I wasn't able to replicate that bug.

**Comment by NiteSite** [comment]
Yeah it is the latest I only have 310. and Like I said it inly happens in the saved beatmaps part no where else. I am trying to clean up duplicates and it sucks having to close it out every 2 deletes but it is better than nothing. Thank you for continuing the work on this

**Comment by ranmd9a** [comment]
Sorry for the late response.

May I ask you to press `ctrl+shift+i` after you sort or delete maps?
The panel should appear as shown in the figure below.
Then go to the console tab. Is there any error?
![20211211-debug](https://user-images.githubusercontent.com/59299733/145619321-441ddc18-a959-43d8-aebd-631e20531288.png)

If no error, unfortunately I can't find a solution.
Please try the following.
- Try temporarily disabling your anti-virus software (including Windows Defender).
- Try reinstalling beatlist by following the steps below.
  https://github.com/ranmd9a/beatlist/wiki/Troubleshooting_en#method-2

**Comment by NiteSite** [comment]
There is an error!

![image](https://user-images.githubusercontent.com/28742845/145636247-6d7a5925-cef3-421a-ba76-0dc8556472da.png)

Let me know if you need anything else!

**Comment by ranmd9a** [comment]
Could you try installing the following file?
And please let me know if you get an error or not.

https://github.com/ranmd9a/beatlist/releases/download/v1.3.4-beta/beatlist.Setup.1.3.4-beta.exe

**Comment by NiteSite** [comment]
> Could you try installing the following file? And please let me know if you get an error or not.
> 
> https://github.com/ranmd9a/beatlist/releases/download/v1.3.4-beta/beatlist.Setup.1.3.4-beta.exe

This 100% fixed the issue!! Thank you so much for the quick replies and help!

**Comment by ranmd9a** [comment]
Thanks for the report!
I'm glad the bug was fixed.
