### ISSUE TITLE
Playlists in subfolders not shown

### ISSUE THREAD

**Issue by symphonic643** [ranmd9a/beatlist#3]
At the moment, it appears that any playlists that have been sorted into subfolders within the playlists folder are not shown in the "My Playlists" tab. I imagine this could be remedied if I just removed the subfolders, but I am hesitant to that as I have many playlists and would like to keep them organized in subfolders, especially for ones I create myself.

**Comment by ranmd9a** [comment]
The beatlist created by Alaanor does not have that feature.
It will take some time to add that feature, so please be patient.

**Comment by ranmd9a** [comment]
Thank you for the report.
Fixed.
https://github.com/ranmd9a/beatlist/releases/tag/v1.3.7

**Comment by symphonic643** [comment]
> Thank you for the report. Fixed. https://github.com/ranmd9a/beatlist/releases/tag/v1.3.7

Thank you for the quick fix!

**Comment by ranmd9a** [comment]
yw. If you have any problems, please create an issue again.
