### ISSUE TITLE
hash値が空白のプレイリストがあるとき読み込みに失敗する

### ISSUE THREAD

**Issue by rakkyo150** [ranmd9a/beatlist#4]
## 問題
プレイリストのファイル名に日本語が含まれているときにプレイリストの読み込みに失敗します。

## 具体的には
ログファイルは無さそうだったので、表面的な挙動のみお伝えします。
追加した複数のプレイリストの中に問題のプレイリストが含まれる場合、UPDATE LIBRARYを押すと、問題のプレイリストの読み込みで止まり、"There is no scan running at the moment."とでてます。
この際、追加したプレイリストはすべてbeatlistに反映されませんでした。
また、一度こうなるとCLEAR CACHEしないと不良キャッシュが残り続けて抜け出せないようです。

### 参考までに
CLEAR CACHEやC:\Users\<ユーザー名>\AppData\Roaming\beatlist以下のファイルを全削除しても効果はなかったです。
なお、ファイル名が英数字のみで中身に日本語が使われている場合は問題ないようです。

## 最後に
お忙しいところ恐縮ですが、ご確認いただくと幸いです。
よろしくお願いします 。

**Comment by ranmd9a** [comment]
ご報告ありがとうございます、確認します<(_ _)>

**Comment by rakkyo150** [comment]
あーちょっとまちがえてました…
今回譜面情報が異常なプレイリストがなぜかあり、巻き込みで他のプレイリストも読み込めなかったので、そこのエラー処理を追加してもらえると、ありがたいといった感じです
一応問題のプレイリストをのぞいてUPDATE LIBRARYすればいいのですが、ユーザー的にはなんで読み込めないのかしばらく分からなかったので

**Comment by rakkyo150** [comment]
今回以上だったのはこの部分でした
以下songsのリストの一要素
```
{
      "songName": "Gurenge",
      "levelAuthorName": "digiracko",
      "key": "",
      "hash": "",
      "levelid": "custom_level_",
      "dateAdded": "2021-05-03T12:49:50.924201+09:00"
},
```

**Comment by ranmd9a** [comment]
なるほど、確かにエラーになりますね。ご報告ありがとうございます、修正します！

**Comment by ranmd9a** [comment]
修正しました、不備などありましたらご連絡ください。<(_ _)>
https://github.com/ranmd9a/beatlist/releases/tag/v1.3.8

**Comment by rakkyo150** [comment]
確認しました～
プレイリスト内のハッシュ情報がおかしな場合はその譜面だけ読み込まれないで動作しました
また、jsonのコンマミスなどでプレイリストそのものが壊れている場合も一応試してみたのですが、そのプレイリストのみが読み込まれないかたちになっていました～
その他の変更も使いやすくていいですね
ありがとうございますm(_ _ )m

**Comment by ranmd9a** [comment]
御確認ありがとうございましたー！
こちらこそ助かりました<(_ _)>
